cloud:
  aws:
    credentials:
      access-key: AKIA3UWQGZRET6UDMEHH
      secret-key: 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
    region:
      static:  us-east-1
    stack:
      auto: false

application:
  bucket:
    name: sawanstorage


spring:
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2MB
      max-file-size: 5MB
      max-request-size: 10MB

server:
  port: 9090

